"""Minimal MCP (Model Context Protocol) JSON-RPC dispatcher.

We implement only the subset required by Claude.ai's remote connector:

- initialize
- tools/list   (returns the read tools (currently 11); the write side adds 14 more)
- tools/call   (dispatches to gmail_tools.dispatch_tool_call)
- ping         (optional liveness)

MCP is JSON-RPC 2.0 over HTTP POST. We accept single requests; batches
are not used by Claude's connector. Notifications (no id) are accepted
silently per the JSON-RPC 2.0 spec.

This module wires tools/list to the gmail_tools.TOOL_DEFINITIONS manifest
and tools/call to gmail_tools.dispatch_tool_call. The
manifest without further changes here.
"""

from __future__ import annotations

import logging
from typing import Any

from . import config as config_module
from .gmail_tools import TOOL_DEFINITIONS as _GMAIL_TOOL_DEFINITIONS
from .gmail_tools import dispatch_tool_call

logger = logging.getLogger(__name__)

PROTOCOL_VERSION = "2025-03-26"
SERVER_NAME = "mcp-gmail"
SERVER_VERSION = "0.1.0"

# Re-exported so server.py and tests can import from mcp_protocol
# without reaching into the gmail_tools package. Aliasing rather than
# copying keeps the two views in sync.
TOOL_DEFINITIONS: list[dict[str, Any]] = _GMAIL_TOOL_DEFINITIONS


def _error_response(req_id: Any, code: int, message: str, data: Any = None) -> dict[str, Any]:
    err: dict[str, Any] = {"code": code, "message": message}
    if data is not None:
        err["data"] = data
    return {"jsonrpc": "2.0", "id": req_id, "error": err}


def _success_response(req_id: Any, result: Any) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "id": req_id, "result": result}


async def handle_jsonrpc(
    message: dict[str, Any],
    claims: dict[str, Any] | None = None,
    correlation_id: str | None = None,
) -> dict[str, Any] | None:
    """Dispatch one JSON-RPC 2.0 message and return the response dict.

    Returns None if the message is a notification (no `id` field), per
    JSON-RPC 2.0. FastAPI will translate None into HTTP 204.

    `claims` is the validated JWT claims dict from the auth layer.
    `correlation_id` is generated by ErrorEnvelopeMiddleware
    and embedded in -32603 internal-error messages instead of the
    exception class name + str (which could leak PII or token-shaped
    content from upstream library exceptions).
    """
    cid = correlation_id or "unknown"
    if not isinstance(message, dict):
        return _error_response(None, -32600, "request must be a JSON object")

    if message.get("jsonrpc") != "2.0":
        return _error_response(message.get("id"), -32600, "jsonrpc must be '2.0'")

    method = message.get("method")
    if not isinstance(method, str):
        return _error_response(message.get("id"), -32600, "method must be a string")

    req_id = message.get("id")
    is_notification = "id" not in message
    params = message.get("params") or {}
    if not isinstance(params, dict):
        return _error_response(req_id, -32602, "params must be an object")

    try:
        if method == "initialize":
            result = {
                "protocolVersion": PROTOCOL_VERSION,
                "capabilities": {"tools": {}},
                "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION},
            }
        elif method == "notifications/initialized":
            return None
        elif method == "ping":
            result = {}
        elif method == "tools/list":
            result = {"tools": list(TOOL_DEFINITIONS)}
        elif method == "tools/call":
            tool_name = params.get("name")
            if not isinstance(tool_name, str) or not tool_name:
                return _error_response(req_id, -32602, "params.name must be a non-empty string")
            arguments = params.get("arguments") or {}
            if not isinstance(arguments, dict):
                return _error_response(req_id, -32602, "params.arguments must be an object")
            # Reject tool names that are not in the manifest. Without
            # this check we would call dispatch_tool_call for a name
            # the dispatcher does not recognize, get back an
            # unknown_error dict, and wrap it as a result rather than
            # the JSON-RPC method-not-found error. The contract for
            # an unrecognized tool is method-not-found.
            registered = {t["name"] for t in TOOL_DEFINITIONS}
            if tool_name not in registered:
                return _error_response(req_id, -32601, f"no tool registered: {tool_name}")
            settings = config_module.load()
            try:
                result = await dispatch_tool_call(
                    tool_name=tool_name,
                    arguments=arguments,
                    claims=claims,
                    settings=settings,
                )
            except Exception:  # noqa: BLE001
                # log full traceback at WARNING with the
                # correlation_id so operators can pivot from the
                # client-visible 32603 to the structured log entry,
                # while keeping PII / library-leaked detail off the
                # wire response.
                logger.warning(
                    "tool dispatch raised (correlation_id=%s)",
                    cid,
                    exc_info=True,
                )
                if is_notification:
                    return None
                return _error_response(
                    req_id,
                    -32603,
                    f"tool dispatch raised (correlation_id={cid})",
                )
            # If the tool returned an error-shaped dict, surface it as
            # a JSON-RPC error so the client gets the standard error
            # envelope. Otherwise wrap as success.
            if isinstance(result, dict) and isinstance(result.get("code"), int):
                code = result.get("code")
                # mypy: code is guaranteed to be an int because of the
                # isinstance check above; assert for the type checker.
                assert isinstance(code, int)
                return _error_response(
                    req_id,
                    code,
                    result.get("message", ""),
                    result.get("data"),
                )
            # MCP spec: tools/call returns content blocks. Wrap the
            # tool result dict in a single text block via JSON encoding
            # so Claude's UI displays something readable. Future
            # iterations can produce richer block types.
            import json as _json

            result = {
                "content": [
                    {"type": "text", "text": _json.dumps(result)},
                ],
                "isError": False,
            }
        else:
            if is_notification:
                return None
            return _error_response(req_id, -32601, f"method not found: {method}")
    except Exception:  # noqa: BLE001
        # same generic-error policy as the inner
        # tool-dispatch path. Full traceback at WARNING with the
        # correlation_id; the wire response only carries the id.
        logger.warning("internal error (correlation_id=%s)", cid, exc_info=True)
        if is_notification:
            return None
        return _error_response(req_id, -32603, f"internal error (correlation_id={cid})")

    if is_notification:
        return None
    return _success_response(req_id, result)
